/**
 * Fiscal Receipt Service - Serbian Fiscalization API (Test Mode)
 *
 * Serbia requires electronic fiscal receipts (e-fiskalizacija) for all transactions.
 * This service integrates with fiscal receipt providers in test mode.
 *
 * Real implementation would use:
 * - SEF (Sistem E-Fiskalizacije) - Official system
 * - V-PFR (Cloud-based fiscal processor for e-commerce)
 * - Certified fiscal receipt service providers
 */

export interface FiscalReceiptItem {
  name: string;
  quantity: number;
  unitPrice: number;
  totalPrice: number;
  taxRate: number; // VAT rate (e.g., 20 for 20%)
}

export interface FiscalReceipt {
  receiptNumber: string;
  fiscalReceiptNumber: string;
  issueDate: string;
  issueTime: string;
  totalAmount: number;
  taxAmount: number;
  items: FiscalReceiptItem[];
  qrCode: string;
  pfrSignature: string; // PFR (Poreski Fiskalni Registar) signature
  businessInfo: {
    name: string;
    taxId: string;
    address: string;
  };
  paymentMethod: string;
  transactionId?: string;
}

export interface FiscalReceiptRequest {
  items: FiscalReceiptItem[];
  totalAmount: number;
  taxAmount: number;
  paymentMethod: string;
  customerInfo?: {
    name?: string;
    email?: string;
    address?: string;
  };
  transactionId?: string;
  metadata?: Record<string, string>;
}

export interface FiscalReceiptResponse {
  success: boolean;
  receipt?: FiscalReceipt;
  error?: string;
  message?: string;
}

/**
 * Send fiscal receipt to Serbian fiscalization system
 * In test mode, this simulates the API call
 */
export async function sendFiscalReceipt(
  request: FiscalReceiptRequest
): Promise<FiscalReceiptResponse> {
  try {
    // In a real implementation, this would call the fiscalization API
    // For Serbia, this typically goes through SEF or a certified provider
    const response = await fetch("/api/fiscal/receipt", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(request),
    });

    if (!response.ok) {
      // Fallback to mock response for test mode
      return createMockFiscalReceipt(request);
    }

    const data = await response.json();
    return {
      success: true,
      receipt: data.receipt,
      message: "Fiscal receipt issued successfully",
    };
  } catch (error) {
    // In test mode, return mock response
    console.log("Using mock fiscal service (test mode)");
    return createMockFiscalReceipt(request);
  }
}

/**
 * Mock Fiscal Receipt for test mode
 * Simulates the Serbian fiscal receipt structure
 */
function createMockFiscalReceipt(
  request: FiscalReceiptRequest
): FiscalReceiptResponse {
  const now = new Date();
  const receiptNumber = `R-${Date.now()}-${Math.random()
    .toString(36)
    .substr(2, 6)
    .toUpperCase()}`;
  const fiscalReceiptNumber = `FIS-${now.getFullYear()}-${String(
    now.getMonth() + 1
  ).padStart(2, "0")}-${receiptNumber}`;

  // Generate mock QR code data (in real implementation, this would be generated by the fiscal system)
  const qrCodeData = {
    rn: fiscalReceiptNumber,
    i: "TEST123456789", // Business tax ID (test)
    t: now.toISOString(),
    a: request.totalAmount,
    s: generateMockPFRSignature(receiptNumber, request.totalAmount),
  };

  const qrCode = `https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=${encodeURIComponent(
    JSON.stringify(qrCodeData)
  )}`;

  const receipt: FiscalReceipt = {
    receiptNumber,
    fiscalReceiptNumber,
    issueDate: now.toISOString().split("T")[0],
    issueTime: now.toTimeString().split(" ")[0],
    totalAmount: request.totalAmount,
    taxAmount: request.taxAmount,
    items: request.items,
    qrCode,
    pfrSignature: generateMockPFRSignature(receiptNumber, request.totalAmount),
    businessInfo: {
      name: "NOOK - Textile Store (TEST)",
      taxId: "TEST123456789",
      address: "123 Textile Street, Belgrade, Serbia",
    },
    paymentMethod: request.paymentMethod,
    transactionId: request.transactionId,
  };

  return {
    success: true,
    receipt,
    message: "Fiscal receipt issued (test mode)",
  };
}

/**
 * Generate mock PFR signature
 * In real implementation, this would be generated by the certified fiscal system
 */
function generateMockPFRSignature(
  receiptNumber: string,
  amount: number
): string {
  // Mock signature generation (in real system, this is cryptographically signed)
  const data = `${receiptNumber}-${amount}-${Date.now()}`;
  return btoa(data).substring(0, 32).toUpperCase();
}

/**
 * Calculate VAT for items
 * Serbia standard VAT rate is 20%
 */
export function calculateVAT(amount: number, vatRate: number = 20): number {
  return Math.round((amount * vatRate) / (100 + vatRate));
}

/**
 * Format fiscal receipt for display
 */
export function formatFiscalReceipt(receipt: FiscalReceipt): string {
  let formatted = `
FISCAL RECEIPT (TEST MODE)
========================
Receipt No: ${receipt.receiptNumber}
Fiscal No: ${receipt.fiscalReceiptNumber}
Date: ${receipt.issueDate} ${receipt.issueTime}

Business: ${receipt.businessInfo.name}
Tax ID: ${receipt.businessInfo.taxId}
Address: ${receipt.businessInfo.address}

Items:
`;

  receipt.items.forEach((item, index) => {
    formatted += `${index + 1}. ${item.name}\n`;
    formatted += `   Qty: ${item.quantity} x ${item.unitPrice.toLocaleString(
      "sr-RS"
    )} RSD\n`;
    formatted += `   Total: ${item.totalPrice.toLocaleString(
      "sr-RS"
    )} RSD (VAT ${item.taxRate}%)\n\n`;
  });

  formatted += `
Subtotal: ${(receipt.totalAmount - receipt.taxAmount).toLocaleString(
    "sr-RS"
  )} RSD
VAT: ${receipt.taxAmount.toLocaleString("sr-RS")} RSD
Total: ${receipt.totalAmount.toLocaleString("sr-RS")} RSD

Payment: ${receipt.paymentMethod}
PFR Signature: ${receipt.pfrSignature}

QR Code: ${receipt.qrCode}
`;

  return formatted;
}
