import { createContext, useContext, useState, ReactNode } from 'react'

type Language = 'en' | 'sr'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations = {
  en: {
    // Navigation
    home: 'Home',
    products: 'Products',
    aboutUs: 'About Us',
    textileCare: 'Textile Care',
    courier: 'Courier',
    favorites: 'Favorites',
    yourFavoritesIsEmpty: 'Your favorites list is empty',
    startAddingToFavorites: 'Start adding items to your favorites',
    removeFromFavorites: 'Remove from favorites',
    cart: 'Cart',
    orders: 'Orders',
    login: 'Login',
    logout: 'Logout',
    myOrders: 'My Orders',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    
    // Home Page
    tableLinenMadeWithLove: 'TABLE LINEN MADE WITH LOVE ❤️',
    heroTitle: "Ćao! It's NOOK",
    heroDescription: 'At NOOK we believe that a home is a place where every object matters. That\'s why we create table linen in small batches, with care for every detail.',
    viewCollection: 'VIEW COLLECTION',
    deliveryHours: 'DELIVERY HOURS',
    deliveryHoursText: 'We accept and deliver orders on weekdays, from 10 AM to 7 PM.',
    ourCollection: 'OUR COLLECTION',
    exceptionalTextiles: 'Exceptional Textiles',
    exceptionalTextilesDescription: 'Each fabric in our collection is chosen for its unique character, quality, and the artistry behind its creation',
    everydayLuxury: 'EVERYDAY LUXURY',
    cotton: 'Cotton',
    cottonDescription: 'Soft, breathable cotton in an array of sophisticated hues and weaves',
    exploreCotton: 'EXPLORE COTTON',
    timelessElegance: 'TIMELESS ELEGANCE',
    linen: 'Linen',
    linenDescription: 'Luxurious linen with an exquisite drape and natural texture',
    exploreLinen: 'EXPLORE LINEN',
    
    // Products
    allProducts: 'All Products',
    filterByCategory: 'Filter by Category',
    backTo: 'Back to',
    items: 'items',
    item: 'item',
    
    // Product Detail
    addToCart: 'Add to Cart',
    size: 'Size',
    fabric: 'Fabric',
    inStock: 'In Stock',
    outOfStock: 'Out of Stock',
    recommendedProducts: 'Recommended Products',
    viewFullscreen: 'View fullscreen',
    
    // Cart
    shoppingCart: 'Shopping Cart',
    yourCartIsEmpty: 'Your cart is empty',
    startAddingItems: 'Start adding items to your cart',
    continueShopping: 'Continue Shopping',
    subtotal: 'Subtotal',
    shipping: 'Shipping',
    total: 'Total',
    proceedToCheckout: 'Proceed to Checkout',
    removeItem: 'Remove item',
    
    // Checkout
    checkout: 'Checkout',
    shippingInformation: 'Shipping Information',
    paymentInformation: 'Payment Information',
    orderSummary: 'Order Summary',
    firstName: 'First Name',
    lastName: 'Last Name',
    email: 'Email',
    phone: 'Phone',
    address: 'Address',
    city: 'City',
    zipCode: 'ZIP Code',
    country: 'Country',
    selectCountry: 'Select Country',
    serbia: 'Serbia',
    other: 'Other',
    cardNumber: 'Card Number',
    cardholderName: 'Cardholder Name',
    expiryDate: 'Expiry Date',
    cvv: 'CVV',
    placeOrder: 'Place Order',
    processingPayment: 'Processing Payment...',
    testModeActive: 'Test Mode Active',
    testCardInfo: 'Use test card:',
    testCardNumber: '4242 4242 4242 4242',
    testCardNote: 'Any expiry date and CVV will work in test mode.',
    
    // Order Confirmation
    orderConfirmed: 'Order Confirmed!',
    thankYouForPurchase: 'Thank you for your purchase. Your order has been received and is being processed.',
    emailSent: 'Email sent!',
    emailSentText: 'We\'ve sent your order confirmation and fiscal receipt to your email address.',
    orderDetails: 'Order Details',
    orderNumber: 'Order Number',
    paymentId: 'Payment ID',
    orderDate: 'Order Date',
    estimatedDelivery: 'Estimated Delivery',
    fiscalReceipt: 'Fiscal Receipt',
    receiptNo: 'Receipt No',
    fiscalNo: 'Fiscal No',
    download: 'Download',
    business: 'Business',
    taxId: 'Tax ID',
    itemsOrdered: 'Items Ordered',
    testModeNotice: 'Test Mode: This is a test fiscal receipt. In production, this receipt would be registered with the Serbian Tax Authority (Poreska Uprava) through the SEF system.',
    whatsNext: "What's Next?",
    whatsNextText: 'You will receive an email confirmation with your order details and tracking information once your order ships.',
    backToHome: 'Back to Home',
    
    // Orders
    myOrders: 'My Orders',
    youHaveNoOrders: 'You have no orders yet',
    ordersCount: 'orders',
    orderCount: 'order',
    noOrdersYet: 'No Orders Yet',
    startShopping: 'Start shopping to see your orders here.',
    browseProducts: 'Browse Products',
    status: 'Status',
    pending: 'Pending',
    processing: 'Processing',
    shipped: 'Shipped',
    delivered: 'Delivered',
    cancelled: 'Cancelled',
    receipt: 'Receipt',
    shippingAddress: 'Shipping Address',
    
    // Login
    welcomeBack: 'Welcome Back',
    signInToAccount: 'Sign in to your account to continue',
    createAccount: 'Create Account',
    signUpToStart: 'Sign up to start shopping',
    fullName: 'Full Name',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    dontHaveAccount: "Don't have an account? Sign up",
    alreadyHaveAccount: 'Already have an account? Sign in',
    signingIn: 'Signing in...',
    creatingAccount: 'Creating account...',
    invalidEmailPassword: 'Invalid email or password',
    emailAlreadyRegistered: 'Email already registered',
    passwordsDoNotMatch: 'Passwords do not match',
    passwordTooShort: 'Password must be at least 6 characters',
    testModeLogin: 'Test Mode: Use any email and password to create an account',
    registrationFailed: 'Registration failed',
    
    // About
    ourStory: 'OUR STORY',
    aboutUsTitle: 'About Us',
    aboutUsDescription: 'We are passionate about bringing you the finest textiles for your home, combining quality craftsmanship with sustainable practices.',
    ourMission: 'Our Mission',
    ourMissionText: 'To provide premium quality textiles that enhance your living spaces while respecting our planet.',
    ourTeam: 'Our Team',
    ourTeamText: 'A dedicated team of textile experts and designers committed to excellence.',
    qualityPromise: 'Quality Promise',
    qualityPromiseText: 'Every product is carefully selected and tested to meet our high standards.',
    ourStoryTitle: 'Our Story',
    ourStoryText1: 'Founded with a vision to transform homes through exceptional textiles, Nook has been serving customers with passion and dedication. We believe that the right textiles can transform any space into a sanctuary of comfort and style.',
    ourStoryText2: 'Our journey began with a simple idea: to make premium quality textiles accessible to everyone. We source our materials from trusted suppliers who share our commitment to sustainability and ethical practices.',
    ourStoryText3: 'Today, we continue to grow and evolve, always staying true to our core values of quality, sustainability, and customer satisfaction.',
    getInTouch: 'GET IN TOUCH',
    contactUs: 'Contact Us',
    emailLabel: 'Email',
    phoneLabel: 'Phone',
    addressLabel: 'Address',
    monFri: 'Mon-Fri: 9AM-6PM',
    
    // Textile Care
    careGuide: 'CARE GUIDE',
    howToCareForTextiles: 'How to Care for Your Textiles',
    properCareDescription: 'Proper care ensures your textiles stay beautiful and last longer. Follow these guidelines to maintain the quality of your purchases.',
    washing: 'Washing',
    washingTip1: 'Always check the care label before washing',
    washingTip2: 'Use cold or warm water (not hot)',
    washingTip3: 'Use mild, eco-friendly detergents',
    washingTip4: 'Wash similar colors together',
    washingTip5: 'Avoid overloading the washing machine',
    drying: 'Drying',
    dryingTip1: 'Air dry when possible to preserve fabric quality',
    dryingTip2: 'Avoid direct sunlight for colored fabrics',
    dryingTip3: 'Use low heat settings if using a dryer',
    dryingTip4: 'Remove promptly to prevent wrinkles',
    dryingTip5: 'Hang or lay flat to maintain shape',
    ironing: 'Ironing',
    ironingTip1: 'Check fabric care label for temperature settings',
    ironingTip2: 'Use steam for stubborn wrinkles',
    ironingTip3: 'Iron on the reverse side for delicate fabrics',
    ironingTip4: 'Never iron directly on prints or embroidery',
    ironingTip5: 'Let fabric cool before storing',
    storage: 'Storage',
    storageTip1: 'Store in a cool, dry place',
    storageTip2: 'Use breathable storage containers',
    storageTip3: 'Avoid plastic bags for long-term storage',
    storageTip4: 'Fold properly to prevent creasing',
    storageTip5: 'Keep away from direct sunlight',
    generalCareGuidelines: 'General Care Guidelines',
    readTheLabel: 'Read the Label:',
    readTheLabelText: 'Always check the care label on your textiles. It contains specific instructions for that particular fabric.',
    sortByColor: 'Sort by Color:',
    sortByColorText: 'Separate whites, lights, and darks to prevent color bleeding.',
    useGentleCycles: 'Use Gentle Cycles:',
    useGentleCyclesText: 'For delicate fabrics, use the gentle or delicate cycle on your washing machine.',
    avoidHarshChemicals: 'Avoid Harsh Chemicals:',
    avoidHarshChemicalsText: 'Use mild detergents and avoid bleach unless specifically recommended.',
    regularMaintenance: 'Regular Maintenance:',
    regularMaintenanceText: 'Regular cleaning and proper storage will extend the life of your textiles significantly.',
    
    // Courier
    shippingDelivery: 'SHIPPING & DELIVERY',
    shippingDeliveryTitle: 'Shipping & Delivery',
    shippingDescription: 'We offer multiple shipping options to get your order to you quickly and safely.',
    standardShipping: 'Standard Shipping',
    standardShippingDescription: 'Regular shipping via Post of Serbia',
    expressShipping: 'Express Shipping',
    expressShippingDescription: 'Fast delivery for urgent orders',
    overnightShipping: 'Overnight Shipping',
    overnightShippingDescription: 'Next day delivery available in major cities',
    businessDays: 'business days',
    businessDay: 'business day',
    ourCourierPartners: 'Our Courier Partners',
    postOfSerbia: 'Post of Serbia',
    postOfSerbiaText: 'Our primary shipping partner for standard deliveries across Serbia. Reliable and cost-effective service.',
    expressCouriers: 'Express Couriers',
    expressCouriersText: 'For express and overnight deliveries, we work with trusted courier services to ensure fast and secure delivery.',
    deliveryAreas: 'Delivery Areas',
    serbiaDelivery: 'Serbia',
    serbiaDeliveryText: 'We deliver to all cities and regions in Serbia. Free shipping available for orders over 10,000 RSD.',
    international: 'International',
    internationalText: 'International shipping available upon request. Please contact us for rates and delivery times.',
    trackingYourOrder: 'Tracking Your Order',
    trackingText: 'Once your order ships, you\'ll receive a tracking number via email. You can use this number to track your package\'s journey to your doorstep.',
    questionsAboutShipping: 'Questions about shipping? Contact us at',
    
    // Orders
    pleaseSignIn: 'Please Sign In',
    needToSignInForOrders: 'You need to be signed in to view your orders.',
    loadingOrders: 'Loading your orders...',
    
    // Common
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    close: 'Close',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    search: 'Search',
    filter: 'Filter',
    clear: 'Clear',
    apply: 'Apply',
    reset: 'Reset',
    next: 'Next',
    previous: 'Previous',
    back: 'Back',
    view: 'View',
    select: 'Select',
    all: 'All',
    none: 'None',
    yes: 'Yes',
    no: 'No',
    ok: 'OK',
    submit: 'Submit',
    required: 'Required',
    optional: 'Optional',
  },
  sr: {
    // Navigation
    home: 'Početna',
    products: 'Proizvodi',
    aboutUs: 'O nama',
    textileCare: 'Negovanje tekstila',
    courier: 'Kurirska služba',
    favorites: 'Omiljeno',
    yourFavoritesIsEmpty: 'Vaša lista omiljenih je prazna',
    startAddingToFavorites: 'Počnite da dodajete proizvode u omiljene',
    removeFromFavorites: 'Ukloni iz omiljenih',
    cart: 'Korpa',
    orders: 'Porudžbine',
    login: 'Prijava',
    logout: 'Odjava',
    myOrders: 'Moje porudžbine',
    signIn: 'Prijavi se',
    signUp: 'Registruj se',
    
    // Home Page
    tableLinenMadeWithLove: 'STOLNJI VES MADE SA LJUBAVLJU ❤️',
    heroTitle: "Ćao! It's NOOK",
    heroDescription: 'U NOOK verujemo da je dom mesto gde svaki predmet ima značaj. Zato kreiramo stolni ves u malim serijama, sa pažnjom prema svakom detalju.',
    viewCollection: 'POGLEDAJ KOLEKCIJU',
    deliveryHours: 'RADNO VREME',
    deliveryHoursText: 'Primamo i isporučujemo porudžbine radnim danima, od 10 do 19 sati.',
    ourCollection: 'NAŠA KOLEKCIJA',
    exceptionalTextiles: 'Izvrsni tekstili',
    exceptionalTextilesDescription: 'Svaka tkanina u našoj kolekciji je odabrana zbog svog jedinstvenog karaktera, kvaliteta i umetnosti koja stoji iza njenog stvaranja',
    everydayLuxury: 'SVAKODNEVNI LUKSUZ',
    cotton: 'Pamuk',
    cottonDescription: 'Mek, prozračan pamuk u nizu sofisticiranih nijansi i tkanja',
    exploreCotton: 'ISTRAŽI PAMUK',
    timelessElegance: 'BEZVREMENSKA ELEGANCIJA',
    linen: 'Lan',
    linenDescription: 'Luksuzni lan sa izvrsnim padom i prirodnom teksturom',
    exploreLinen: 'ISTRAŽI LAN',
    
    // Products
    allProducts: 'Svi proizvodi',
    filterByCategory: 'Filtriraj po kategoriji',
    backTo: 'Nazad na',
    items: 'proizvoda',
    item: 'proizvod',
    
    // Product Detail
    addToCart: 'Dodaj u korpu',
    size: 'Veličina',
    fabric: 'Tkanina',
    inStock: 'Na stanju',
    outOfStock: 'Nema na stanju',
    recommendedProducts: 'Preporučeni proizvodi',
    viewFullscreen: 'Pogledaj u punom ekranu',
    
    // Cart
    shoppingCart: 'Korpa za kupovinu',
    yourCartIsEmpty: 'Vaša korpa je prazna',
    startAddingItems: 'Počnite da dodajete proizvode u korpu',
    continueShopping: 'Nastavi kupovinu',
    subtotal: 'Međuzbir',
    shipping: 'Dostava',
    total: 'Ukupno',
    proceedToCheckout: 'Nastavi na plaćanje',
    removeItem: 'Ukloni proizvod',
    
    // Checkout
    checkout: 'Plaćanje',
    shippingInformation: 'Podaci za dostavu',
    paymentInformation: 'Podaci za plaćanje',
    orderSummary: 'Pregled porudžbine',
    firstName: 'Ime',
    lastName: 'Prezime',
    email: 'Email',
    phone: 'Telefon',
    address: 'Adresa',
    city: 'Grad',
    zipCode: 'Poštanski broj',
    country: 'Država',
    selectCountry: 'Izaberi državu',
    serbia: 'Srbija',
    other: 'Drugo',
    cardNumber: 'Broj kartice',
    cardholderName: 'Ime vlasnika kartice',
    expiryDate: 'Datum isteka',
    cvv: 'CVV',
    placeOrder: 'Poruči',
    processingPayment: 'Obrada plaćanja...',
    testModeActive: 'Test režim aktivan',
    testCardInfo: 'Koristi test karticu:',
    testCardNumber: '4242 4242 4242 4242',
    testCardNote: 'Bilo koji datum isteka i CVV će raditi u test režimu.',
    
    // Order Confirmation
    orderConfirmed: 'Porudžbina potvrđena!',
    thankYouForPurchase: 'Hvala vam na kupovini. Vaša porudžbina je primljena i obrađuje se.',
    emailSent: 'Email poslat!',
    emailSentText: 'Poslali smo potvrdu porudžbine i fiskalni račun na vašu email adresu.',
    orderDetails: 'Detalji porudžbine',
    orderNumber: 'Broj porudžbine',
    paymentId: 'ID plaćanja',
    orderDate: 'Datum porudžbine',
    estimatedDelivery: 'Procenjeno vreme dostave',
    fiscalReceipt: 'Fiskalni račun',
    receiptNo: 'Broj računa',
    fiscalNo: 'Fiskalni broj',
    download: 'Preuzmi',
    business: 'Preduzeće',
    taxId: 'Poreski broj',
    itemsOrdered: 'Naručeni proizvodi',
    testModeNotice: 'Test režim: Ovo je test fiskalni račun. U produkciji, ovaj račun bi bio registrovan kod Poreske uprave kroz SEF sistem.',
    whatsNext: 'Šta je sledeće?',
    whatsNextText: 'Primićete email potvrdu sa detaljima porudžbine i informacijama za praćenje kada se vaša porudžbina pošalje.',
    backToHome: 'Nazad na početnu',
    
    // Orders
    myOrders: 'Moje porudžbine',
    youHaveNoOrders: 'Nemate još porudžbina',
    ordersCount: 'porudžbina',
    orderCount: 'porudžbina',
    noOrdersYet: 'Još nema porudžbina',
    startShopping: 'Počnite kupovinu da biste videli svoje porudžbine ovde.',
    browseProducts: 'Pregledaj proizvode',
    status: 'Status',
    pending: 'Na čekanju',
    processing: 'U obradi',
    shipped: 'Poslato',
    delivered: 'Isporučeno',
    cancelled: 'Otkazano',
    receipt: 'Račun',
    shippingAddress: 'Adresa za dostavu',
    
    // Login
    welcomeBack: 'Dobrodošli nazad',
    signInToAccount: 'Prijavite se na svoj nalog da biste nastavili',
    createAccount: 'Kreiraj nalog',
    signUpToStart: 'Registrujte se da biste počeli kupovinu',
    fullName: 'Ime i prezime',
    password: 'Lozinka',
    confirmPassword: 'Potvrdi lozinku',
    dontHaveAccount: 'Nemate nalog? Registrujte se',
    alreadyHaveAccount: 'Već imate nalog? Prijavite se',
    signingIn: 'Prijavljivanje...',
    creatingAccount: 'Kreiranje naloga...',
    invalidEmailPassword: 'Nevažeći email ili lozinka',
    emailAlreadyRegistered: 'Email je već registrovan',
    passwordsDoNotMatch: 'Lozinke se ne poklapaju',
    passwordTooShort: 'Lozinka mora imati najmanje 6 karaktera',
    testModeLogin: 'Test režim: Koristite bilo koji email i lozinku da kreirate nalog',
    registrationFailed: 'Registracija nije uspela',
    
    // About
    ourStory: 'NAŠA PRIČA',
    aboutUsTitle: 'O nama',
    aboutUsDescription: 'Strastveni smo u donošenju najfinijih tekstila za vaš dom, kombinujući kvalitetan zanat sa održivim praksama.',
    ourMission: 'Naša misija',
    ourMissionText: 'Da pružimo tekstile vrhunskog kvaliteta koji poboljšavaju vaše životne prostore dok poštujemo našu planetu.',
    ourTeam: 'Naš tim',
    ourTeamText: 'Posvećen tim stručnjaka za tekstil i dizajnera posvećenih izvrsnosti.',
    qualityPromise: 'Obećanje kvaliteta',
    qualityPromiseText: 'Svaki proizvod je pažljivo odabran i testiran da ispuni naše visoke standarde.',
    ourStoryTitle: 'Naša priča',
    ourStoryText1: 'Osnovani sa vizijom transformacije domova kroz izuzetne tekstile, Nook posluje sa strastvenošću i posvećenošću. Verujemo da pravi tekstili mogu transformisati bilo koji prostor u utočište udobnosti i stila.',
    ourStoryText2: 'Naše putovanje je počelo jednostavnom idejom: da učinimo tekstile vrhunskog kvaliteta dostupnim svima. Nabavljamo materijale od pouzdanih dobavljača koji dele našu posvećenost održivosti i etičkim praksama.',
    ourStoryText3: 'Danas nastavljamo da rastemo i evoluiramo, uvek ostajući verni našim osnovnim vrednostima: kvalitetu, održivosti i zadovoljstvu kupaca.',
    getInTouch: 'KONTAKTIRAJTE NAS',
    contactUs: 'Kontakt',
    emailLabel: 'Email',
    phoneLabel: 'Telefon',
    addressLabel: 'Adresa',
    monFri: 'Pon-Pet: 9-18h',
    
    // Textile Care
    careGuide: 'VODIČ ZA NEGU',
    howToCareForTextiles: 'Kako da negujete svoje tekstile',
    properCareDescription: 'Pravilna nega osigurava da vaši tekstili ostanu lepi i traju duže. Pratite ove smernice da održite kvalitet svojih kupovina.',
    washing: 'Pranje',
    washingTip1: 'Uvek proverite etiketu za negu pre pranja',
    washingTip2: 'Koristite hladnu ili toplu vodu (ne vrelu)',
    washingTip3: 'Koristite blage, ekološke deterdžente',
    washingTip4: 'Perite slične boje zajedno',
    washingTip5: 'Izbegavajte preopterećenje mašine za pranje',
    drying: 'Sušenje',
    dryingTip1: 'Sušite na vazduhu kada je moguće da sačuvate kvalitet tkanine',
    dryingTip2: 'Izbegavajte direktno sunce za obojene tkanine',
    dryingTip3: 'Koristite niske temperature ako koristite sušilicu',
    dryingTip4: 'Uklonite na vreme da sprečite gužvanje',
    dryingTip5: 'Obesite ili položite ravno da zadržite oblik',
    ironing: 'Peglanje',
    ironingTip1: 'Proverite etiketu za negu za temperature',
    ironingTip2: 'Koristite paru za tvrdoglave nabore',
    ironingTip3: 'Peglajte na naličju za delikatne tkanine',
    ironingTip4: 'Nikada ne peglajte direktno na printove ili vez',
    ironingTip5: 'Pustite tkaninu da se ohladi pre čuvanja',
    storage: 'Čuvanje',
    storageTip1: 'Čuvajte na hladnom, suvom mestu',
    storageTip2: 'Koristite prozračne kontejnere za čuvanje',
    storageTip3: 'Izbegavajte plastične kesice za dugotrajno čuvanje',
    storageTip4: 'Sklopite pravilno da sprečite gužvanje',
    storageTip5: 'Čuvajte dalje od direktnog sunca',
    generalCareGuidelines: 'Opšte smernice za negu',
    readTheLabel: 'Pročitajte etiketu:',
    readTheLabelText: 'Uvek proverite etiketu za negu na vašim tekstilima. Sadrži specifične instrukcije za tu određenu tkaninu.',
    sortByColor: 'Sortiraj po boji:',
    sortByColorText: 'Odvojite belo, svetlo i tamno da biste sprečili mešanje boja.',
    useGentleCycles: 'Koristite blage programe:',
    useGentleCyclesText: 'Za delikatne tkanine, koristite blagi ili delikatni program na vašoj mašini za pranje.',
    avoidHarshChemicals: 'Izbegavajte agresivne hemikalije:',
    avoidHarshChemicalsText: 'Koristite blage deterdžente i izbegavajte izbeljivač osim ako nije posebno preporučeno.',
    regularMaintenance: 'Redovno održavanje:',
    regularMaintenanceText: 'Redovno čišćenje i pravilno čuvanje značajno će produžiti životni vek vaših tekstila.',
    
    // Courier
    shippingDelivery: 'DOSTAVA',
    shippingDeliveryTitle: 'Dostava',
    shippingDescription: 'Nudimo više opcija dostave da bismo vam brzo i sigurno isporučili porudžbinu.',
    standardShipping: 'Standardna dostava',
    standardShippingDescription: 'Redovna dostava preko Pošte Srbije',
    expressShipping: 'Ekspres dostava',
    expressShippingDescription: 'Brza dostava za hitne porudžbine',
    overnightShipping: 'Dostava preko noći',
    overnightShippingDescription: 'Dostava sutradan dostupna u većim gradovima',
    businessDays: 'radnih dana',
    businessDay: 'radni dan',
    ourCourierPartners: 'Naši kurirski partneri',
    postOfSerbia: 'Pošta Srbije',
    postOfSerbiaText: 'Naš glavni partner za standardne dostave širom Srbije. Pouzdana i isplativa usluga.',
    expressCouriers: 'Ekspres kuriri',
    expressCouriersText: 'Za ekspres i dostave preko noći, radimo sa pouzdanim kurirskim službama da osiguramo brzu i sigurnu dostavu.',
    deliveryAreas: 'Oblasti dostave',
    serbiaDelivery: 'Srbija',
    serbiaDeliveryText: 'Isporučujemo u sve gradove i regije u Srbiji. Besplatna dostava za porudžbine preko 10.000 RSD.',
    international: 'Međunarodno',
    internationalText: 'Međunarodna dostava dostupna na zahtev. Kontaktirajte nas za cene i vreme dostave.',
    trackingYourOrder: 'Praćenje vaše porudžbine',
    trackingText: 'Kada se vaša porudžbina pošalje, primićete broj za praćenje putem emaila. Možete koristiti ovaj broj da pratite putovanje vašeg paketa do vaših vrata.',
    questionsAboutShipping: 'Pitanja o dostavi? Kontaktirajte nas na',
    
    // Orders
    pleaseSignIn: 'Molimo prijavite se',
    needToSignInForOrders: 'Morate biti prijavljeni da biste videli svoje porudžbine.',
    loadingOrders: 'Učitavanje vaših porudžbina...',
    
    // Common
    loading: 'Učitavanje...',
    error: 'Greška',
    success: 'Uspešno',
    close: 'Zatvori',
    cancel: 'Otkaži',
    save: 'Sačuvaj',
    delete: 'Obriši',
    edit: 'Izmeni',
    search: 'Pretraži',
    filter: 'Filtriraj',
    clear: 'Obriši',
    apply: 'Primeni',
    reset: 'Resetuj',
    next: 'Sledeće',
    previous: 'Prethodno',
    back: 'Nazad',
    view: 'Pogledaj',
    select: 'Izaberi',
    all: 'Sve',
    none: 'Ništa',
    yes: 'Da',
    no: 'Ne',
    ok: 'OK',
    submit: 'Pošalji',
    required: 'Obavezno',
    optional: 'Opciono',
  },
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language')
    return (saved === 'sr' || saved === 'en' ? saved : 'en') as Language
  })

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang)
    localStorage.setItem('language', lang)
  }

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
